export const STARTERS_DATA_KEY = 'STARTERS_DATA_KEY'
export const MAIN_COURSES_DATA_KEY = 'MAIN_COURSES_DATA_KEY'
export const DRINKS_DATA_KEY = 'DRINKS_DATA_KEY'
export const SNACKS_DATA_KEY = 'SNACKS_DATA_KEY'
export const DESSERTS_DATA_KEY = 'DESSERTS_DATA_KEY'

